name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Check out repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Dependencies installed successfully!"

    # Custom message before running tests
    - name: Prepare to run tests
      run: echo "Running tests now..."

    # Run tests with a custom message
    - name: Run tests
      run: |
        echo "Starting pytest..."
        pytest || echo "Tests failed, check the logs for details."
        echo "Tests completed."

    # Custom message at the end of the job
    - name: Final message
      run: echo "CI pipeline completed!"
